### ISSUE TITLE
No text coloring?

### ISSUE THREAD

**Issue by HarelM** [OpenCoverUI/OpenCover.UI#104]
After a successful run of code coverage, when double clicking the function - the code is not highlighted in red and green colors? am I missing something?
VS 2015 community.

**Comment by pver** [comment]
Did you enable the color and/or glyph buttons? You can find these in the OpenCover Results window (the 2 buttons on the left)

**Comment by HarelM** [comment]
Thanks! Missed those buttons...
A wiki page with instructions might help too:-)

**Comment by pver** [comment]
True, we really need to extend the documentation soon :-)

In case you don't like the default colors (for instance depending on your VS theme), here you can find a guide to change them: https://github.com/OpenCoverUI/OpenCover.UI/wiki/OpenCover.UI-Configuration
