### ISSUE TITLE
add menu item to turn off coverage coloring

### ISSUE THREAD

**Issue by gregveres** [OpenCoverUI/OpenCover.UI#123]
I really like OpenCover.UI. Thank you for writing it. I find that the coloring in the editor window can get in the way and annoying when I am done with it. 

What I usually do is write the unit test and code based on requirements. Then when I feel I have finished implementing the requirements and covering those requirements with unit tests, I turn to a code coverage tool to tell me where I need to write my failing test cases or test cases that I didn't think of. So I run OpenCover.UI to get my code coverage. This shows me that I need to write a couple unit tests, which I do. Then I will run the coverage test run again to see if I covered everything.

But when I go back to writing more code, the coloring gets in the way. So I would really love a menu item under OpenCover or something that turns off the coloring until the next coverage run. That way I could get back to coding without having to shut down VS and relaunch it just to get rid of the colors. 

Thanks for listening.
Greg

**Comment by pver** [comment]
Hi @gregveres, nice to hear you like the extension!

You can disable the coverage coloring by using the 2 left buttons in the Coverage Results window: you can enable and disable the line coloring or the glyps in the left editor bar separately

![image](https://cloud.githubusercontent.com/assets/1618378/13840869/9dc455c2-ec25-11e5-8e4d-4e9a8acfccc7.png)

I think this is what you are looking for?

**Comment by gregveres** [comment]
Perfect. Yes that was exactly what I was looking for. Thank you for pointing it out.

**Comment by pver** [comment]
Ok, no problem!
