### ISSUE TITLE
Add goto unit test definition from Test Explorer

### ISSUE THREAD

**Issue by jamdagni86** [OpenCoverUI/OpenCover.UI#13]
Add support to goto source file when double clicked on a unit test from OpenCover Test Explorer

**Comment by pver** [comment]
Got this working. I'll do some further testing with different test and project setups, but you can expect a PR soon

**Comment by sawilde** [comment]
awesome

**Comment by pver** [comment]
The search does not traverse through all subfolders/namespaces yet (and therefor can't open every discovered test yet).
I'll fix this
