### ISSUE TITLE
Code coverage coloring on black version of VS2015

### ISSUE THREAD

**Issue by qbodart** [OpenCoverUI/OpenCover.UI#154]
### Issue description:
Code coverage coloring makes the code unreadable when you are using VS2015 in "black mode". Ideally, your setting page would allow us to change the colors.

### Versions used:
- OpenCover exe:
- OpenCover.UI:
- Visual Studio (inc. SP number): 
- MsTest/NUnit/xUnit:

**Comment by pver** [comment]
> Ideally, your setting page would allow us to change the colors.

That's actually already possible ;-)
See: https://github.com/OpenCoverUI/OpenCover.UI/wiki/OpenCover.UI-Configuration

**Comment by qbodart** [comment]
Thanks!
