### ISSUE TITLE
Support Xunit tests

### ISSUE THREAD

**Issue by csMACnz** [OpenCoverUI/OpenCover.UI#27]
I notice your plugin works for mstest and nunit tests.  It would be great if this also supported XUnit as well. This is the test framework I am using with opencover on the command line already.

This might be something I can look at forking myself in a few months, but if this is something others are looking at already that would be awesome.

**Comment by csmacnz** [comment]
No worries @sawilde, its good to see how these transitions happen.  

@jamdagni86 I'll look to find some time to add xunit support and flick through a PR at some point, sounds like you will be busy enough with your bug fixes and handover :)

**Comment by AtwooTM** [comment]
@sawilde @jamdagni86 @csMACnz Do you guys need help with xUnit support?  If someone has already started working on it, do need a collaborator?  If no one has started, I may give it a try in some free development cycles...

**Comment by pver** [comment]
Some work has started here: https://github.com/OpenCoverUI/OpenCover.UI/pull/69
but we didn't verify it yet. It might be a good starting point. I don't have much experience with xUnit so it would be great if you could do some verifications with it

**Comment by xied75** [comment]
:+1: Would be great if someone do this work.

**Comment by messerm** [comment]
+1

**Comment by lorenh** [comment]
Is anyone working on merging in the xunit support?  We could sure use it.

**Comment by lorenh** [comment]
I see Joshlrogers updated his PR that adds support for XUnit.  It would be awesome if this could get merged someday!

**Comment by hesantan** [comment]
We are eagerly waiting for xUnit support also. Any plans when support will be merged back in to the main branch?

**Comment by MelleKoning** [comment]
Hi all,

A pull request is in for xunit support, based on the work from @joshlrogers 

Please feel free to checkout the pull request and test it, as I only tested with VS2015sp3 and it is always good to have more experiences.

**Comment by xied75** [comment]
@MelleKoning Tried pull 148, VS solution compiles fine, under Debug mode got the vsix and installed it. Able to run xunit test after pointing it to xunit console runner and opencover console exe. Also using VS2015up3 here.

Great work!

**Comment by MelleKoning** [comment]
Thank you @xied75 ! @pver can you please merge the xUnit pull request?

**Comment by hesantan** [comment]
@mellekoning @xied75 @pver This might be obvious, but ai just wanted to mention that the NuGet package should be updated with the new release. Thank s guys!

**Comment by pver** [comment]
See #148

**Comment by Jerome2606** [comment]
Hello,

I have version 0.8.1 installed but cannot see my Xunit tests in test explorer.

Do I need to get other beta version ?
