### ISSUE TITLE
Visual Studio Theme Support

### ISSUE THREAD

**Issue by Steve-Fenton** [OpenCoverUI/OpenCover.UI#28]
Firstly, thanks for this excellent Visual Studio extension.

Would it be possible to respect the Visual Studio theme? I am using the standard "Dark" theme and it doesn't get properly applied to the two OpenCover UI windows. In some cases, the background is the one from the theme (dark grey) but the foreground is still the default black text, which is hard to read.

**Comment by jamdagni86** [comment]
Hi,

I've started the process of moving away from the plugin development (as I no longer have access to Windows and Visual Studio) and Shaun Wilde - the creator of OpenCover - has agreed to take the plugin forward. I had created an issue in Github to track the theme support feature. But I couldn't finish it.

**Comment by sawilde** [comment]
I have agreed to help take it forward but I need some handover information as requested previously.

**Comment by Beronien** [comment]
In the meantime, there is any way of manually set up the window style of the OpenCover UI windows? I have been searching them in the options but I could not find them. Wich window group are they?

**Comment by pver** [comment]
I don't think there's an option for this at the moment (at least I didn't came across one while exploring the code of the plugin)

As a side note: I've already made some progress in making the plugin use the Visual Studio theme colors. I'll create a PR once it's completely finished.

**Comment by sawilde** [comment]
@pver awesome 

I've actually been tidying up a new feature in OpenCover so I can have a clear mind for when I start to look at this code base - so more hands the merrier.

**Comment by pver** [comment]
A sneak preview of the changes (it follows the selected Visual Studio theme dynamically when it's changed) :
*Dark theme*
![image](https://cloud.githubusercontent.com/assets/1618378/6157907/86ac3104-b245-11e4-9e36-71b7b9d18daa.png)
*Blue theme*
![image](https://cloud.githubusercontent.com/assets/1618378/6157940/d9786ed4-b245-11e4-89dc-a6f46d7a05f5.png)
*Light theme*
![image](https://cloud.githubusercontent.com/assets/1618378/6157959/159b1d8a-b246-11e4-8c88-2ba3ef8c96ff.png)


Still some work on the column header styling, but I hope to finish it in the coming days!

**Comment by sawilde** [comment]
awesome :)

**Comment by Steve-Fenton** [comment]
Looks great - and solves major readability problems :)

**Comment by twenzel** [comment]
Great! Any plans for the next release date? ;)

**Comment by pver** [comment]
Took a bit longer than expected, but #37 should make sure the plugin supports the VS themes :)

**Comment by sawilde** [comment]
awesome - I am currently sorting out teams - I'll update the wiki with plans
