### ISSUE TITLE
Missing support for VB.NET projects

### ISSUE THREAD

**Issue by twenzel** [OpenCoverUI/OpenCover.UI#30]
No tests where discovered when using VB.NET.

Please add the project GUID "F184B08F-C81C-45F6-A57F-5ABD9991F28F" to IDEHelper.GetProjects().

**Comment by jamdagni86** [comment]
@twenzel - I guess you will have to edit OpenCover.UI/OpenCover.UI/Tagger/TextTaggerProvider.cs file to add ContentTypeAttribute on TextTaggerProvider so that the file opened through the test results window will color code the source properly.
