### ISSUE TITLE
Support for 64bit machine

### ISSUE THREAD

**Issue by twenzel** [OpenCoverUI/OpenCover.UI#31]
If you work on a x64 machine and your project output is defined as x86 then you should use the nunit-console-x86.exe. otherwise no test can be executed and a BadImageFormatException will be thrown.

So you should discover the target platform for the selected tests in NUnitTestExecutor and determine whether you are running on ax64 machine.

**Comment by pver** [comment]
@sawilde if you want I can take a look at this one: I noticed the same problem for one of my projects so I can already reproduce this

**Comment by sawilde** [comment]
Sure - I am adding teams to help manage ownership of tasks (assuming people want to claim them) :)

**Comment by pver** [comment]
:+1: perfect! :)

**Comment by twenzel** [comment]
I've already solved this one in my repro.
https://github.com/twenzel/OpenCover.UI/commit/2e71e4d0de85a375506afd4194039e09e21ffd54
@pver If it's ok to you I can create a pull request.

**Comment by pver** [comment]
> @pver If it's ok to you I can create a pull request.

Sure, the fix looks good! :+1:
