### ISSUE TITLE
Show line coverage in code editor

### ISSUE THREAD

**Issue by twenzel** [OpenCoverUI/OpenCover.UI#32]
Please show the coverage state for each line in the code editor. This will improve the usage of this extension. Otherwise I won't see which line was not affected through my tests and need to be tested.

This is a minimum requirement for version 1.0.

**Comment by pver** [comment]
@twenzel it is possible to see the line coverage by double clicking on an item in the coverage results window. This will open the file in the code editor and highlight the covered and uncovered lines of code. It should look like this:
![image](https://cloud.githubusercontent.com/assets/1618378/6186805/e2a0569a-b37e-11e4-9196-841214a5710a.png)

(I noticed the double click does not work everywhere yet, for instance double clicking on an autoproperty does not open the editor. But it should already work on most of the items in the coverage results window. I'll open a separate issue to follow that up)

**Comment by twenzel** [comment]
Great. Maybe it does not work for VB.NET projects. I will check this.

**Comment by pver** [comment]
Good point, haven't tried it with VB.Net yet. Keep us posted! :)

**Comment by twenzel** [comment]
Gotcha! Done by https://github.com/twenzel/OpenCover.UI/commit/4d4a41cdedc71e12b2e8de3108dbb8c895c542c3

**Comment by sawilde** [comment]
we should be able to support any .net language - opencover doesn't care
