### ISSUE TITLE
Setup Slack for team communication

### ISSUE THREAD

**Issue by sawilde** [OpenCoverUI/OpenCover.UI#40]
Hi guys, I have set up a slack account to help those of us working on the UI to communicate (github is so limited) and perhaps get to know each other better.

@jamdagni86 
@pver 
@twenzel
@csMACnz

visit the [team page](https://opencoverui.slack.com/) to sign up and join the conversation.

**Comment by pver** [comment]
Good idea!
I tried to join the team, but the site (https://opencoverui.slack.com/) says we need an invitation from the team admin to be able to join. And if I try to register first in the Slack home page, it wants to create a new team. I haven't worked with Slack before, so maybe I'm doing something wrong?

**Comment by sawilde** [comment]
hmmm... damn I didn't realize its invitation only - or limited to domains grrr...

okay, looks like it's invite only - I'll update the readme

if you want an invite - post below - feel free to obfuscate your email (but not so much I can't work it out)

**Comment by pver** [comment]
@sawilde no problem, you can use the following (obfuscated) mailadres for the invite: 'depezor at yahoosmail.com'

**Comment by twenzel** [comment]
Yep, use mine toni (dot) wenzel (at) googlemail.com

**Comment by sawilde** [comment]
sent - if you don't get an email let me know

**Comment by pver** [comment]
I didn't receive the mail yet, I might have obfuscated my mail address too much :)
Before the 'at' it's 'depezor' and after the at it's 'yahoo.com'

**Comment by sawilde** [comment]
tried again :)

**Comment by pver** [comment]
Got it now, thanks! :)

**Comment by sawilde** [comment]
awesome

**Comment by sawilde** [comment]
let's see how this goes - we may want to try others such as [glitter](https://gitter.im)

**Comment by tekkies** [comment]
Would it be possible to get an invite to slack - I'm trying to nail a bug affecting me and a friend?
andy dot joiner at tekkies dot co dot uk

**Comment by sawilde** [comment]
we switched to gitter as we wanted the least amount of effort involved to get people talking - link should be on the home page for the repo

**Comment by tekkies** [comment]
The links in the Team communication section on the [ReadMe.md](https://github.com/OpenCoverUI/OpenCover.UI/blob/master/README.md) still seems to point to slack.

**Comment by tekkies** [comment]
I think I found the page by googling :)

**Comment by sawilde** [comment]
you're right need to change that - I thought the big gitter button would help though :)
