### ISSUE TITLE
TextTagger throws exception

### ISSUE THREAD

**Issue by pver** [OpenCoverUI/OpenCover.UI#58]
I got error this with the current master (not sure how to reproduce it yet) :

> System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at OpenCover.UI.Tagger.TextTagger..ctor(ITextView view, ITextSearchService searchService, IClassificationType coveredType, IClassificationType notCoveredType) at OpenCover.UI.Tagger.TextTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer) at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)

I'll see if I can get more context for this error (it only happened once)

**Comment by pver** [comment]
@twenzel I think it should work if we add a check if the item is already added here: https://github.com/OpenCoverUI/OpenCover.UI/blob/82d52c4f8400b941d34b292247c2e7d4adda0ef5/OpenCover.UI/Tagger/TextTagger.cs#L52

But maybe this indicates another problem? Maybe it shouldn't happen at all that it tries to add it the view twice? Do you have an idea (I'm not very familiar with the TextTagger yet)?

**Comment by twenzel** [comment]
I was also not able to reproduce this issue.
But I added a little logic to return the already registered tagger instance instead of creating a new one.

**Comment by pver** [comment]
:+1: Nice! 
It's a strange issue indeed: I only notice it once every Visual Studio session (always several seconds after VS starts), and only on one of my machines. Maybe it's because of using OpenCover.UI in combination with another tool that does something with Taggers (I only noticed it on a machine with Resharper and DotCover, but that might be completely coincidence)
