### ISSUE TITLE
NRE in TextTagger.Dispose

### ISSUE THREAD

**Issue by pver** [OpenCoverUI/OpenCover.UI#61]
I got these errors in my ActivityLog.xml. I think the dispose is called more than once, causing subsequent disposes to fail

> 934 ERROR System.NullReferenceException: Object reference not set to an instance of an object. at OpenCover.UI.Tagger.TextTagger.Dispose(Boolean disposing) at OpenCover.UI.Helper.TextViewCoverageProviderBase.Dispose() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<>c__DisplayClass3a.<UnregisterTagger>b__38() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)   Editor or Editor Extension 2015/04/08 11:20:27.500 
935 ERROR System.NullReferenceException: Object reference not set to an instance of an object. at OpenCover.UI.Tagger.TextTagger.Dispose(Boolean disposing) at OpenCover.UI.Helper.TextViewCoverageProviderBase.Dispose() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<>c__DisplayClass3a.<UnregisterTagger>b__38() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)   Editor or Editor Extension 2015/04/08 11:20:27.501 
936 ERROR System.NullReferenceException: Object reference not set to an instance of an object. at OpenCover.UI.Tagger.TextTagger.Dispose(Boolean disposing) at OpenCover.UI.Helper.TextViewCoverageProviderBase.Dispose() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<>c__DisplayClass3a.<UnregisterTagger>b__38() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)   Editor or Editor Extension 2015/04/08 11:20:27.501 
937 ERROR System.NullReferenceException: Object reference not set to an instance of an object. at OpenCover.UI.Tagger.TextTagger.Dispose(Boolean disposing) at OpenCover.UI.Helper.TextViewCoverageProviderBase.Dispose() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<>c__DisplayClass3a.<UnregisterTagger>b__38() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)   Editor or Editor Extension 2015/04/08 11:20:27.501 
938 ERROR System.NullReferenceException: Object reference not set to an instance of an object. at OpenCover.UI.Tagger.TextTagger.Dispose(Boolean disposing) at OpenCover.UI.Helper.TextViewCoverageProviderBase.Dispose() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<>c__DisplayClass3a.<UnregisterTagger>b__38() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)   Editor or Editor Extension 2015/04/08 11:20:27.501

**Comment by twenzel** [comment]
I'm not able to reproduce this error. But if the Dispose method is realy called twice the fix should work.
