### ISSUE TITLE
cant get opencover to run in vs2012

### ISSUE THREAD

**Issue by gsuttie** [OpenCoverUI/OpenCover.UI#95]
I installed using the vsix from the extension update manager inside vs 2012 and I get an nunit window popup when trying to run the coverage on a test

**Comment by pver** [comment]
The extension uses NUnit to execute the unit tests, but NUnit should be installed separately on your machine (see http://nunit.org/index.php?p=download )
The first time you run the extension, a popup is shown to indicate NUnit could not be found (yet). After closing this popup window, you can then point to the nunit console runner. 

You can also set the nunit path from the options dialog: ![Image of settings dialog](https://cloud.githubusercontent.com/assets/1618378/9236304/5ef348ee-4144-11e5-8c73-f85d153539da.png)

Could you try it again with the correct NUnit path configured? I also use the plugin in VS2012, so normally it should be compatible

**Comment by gsuttie** [comment]
Hi there, got it working many many thanks, Is there away to exclude .test projects from coverage results?

**Comment by pver** [comment]
You're welcome, good to hear you have it working :+1: 

Excluding projects (or referenced assemblies) is not supported yet, but it's indeed a good feature and it's on definitely our todo list: OpenCoverUI/OpenCover.UI/issues/44

**Comment by pver** [comment]
The initial issue was resolved and other remaining item can be tracked here: #44
