### ISSUE TITLE
VS2015, MSTest, OpenCover only covers external dll's

### ISSUE THREAD

**Issue by JoeAtGit** [OpenCoverUI/OpenCover.UI#96]
shows coverage for moq.dll and EntitiyFramework.BulkInsert.dll; not for the project being covered.

any idea is welcome

thanks

**Comment by pver** [comment]
Hi @JoeAtGit, thanks for reporting this.
I noticed you also created a ticket in the OpenCover project (OpenCover/opencover/issues/356). It looks like you don't get any results when your run OpenCover itself either? Or is it unrelated to this issue?

**Comment by JoeAtGit** [comment]
Thank you Peter

Those are unrelated, issue with OpenCover via cmd is sorted.

**Comment by JoeAtGit** [comment]
Apologies Peter, post further investigation, it seems it is OpenCover related.

**Comment by pver** [comment]
No problem! :+1:
